#%RAML 1.0 DataType
type: object
properties:
  streetAddress:
    type: string
    example: John
    required: false 
  city:
    type: string
    example: John
    required: false 
  state:
    type: string
    example: John
    required: false 
  postalCode:
    type: number
    example: 10023
    required: false 