#%RAML 1.0
title: Xandr-sAPI
mediaType: 
- application/json
protocols:
  - HTTP

/advertisers:
  put:
    body:
      application/json:
        type: !include ../DataTypes/dataType-Xandr.raml
        example: !include ../example/xandr.json
    responses:
      200:
        description: ok
        
/insertion-orders:
  post:
    body:
      application/json:
        type: !include ../DataTypes/dataType-Xandr.raml
        example: !include ../example/xandr.json
    responses:
      200:
        description: ok